#数据库连接信息
spring:
        datasource:
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/lost_and_found?characterEncoding=UTF-8&useUnicode=true&useSSL=false
                username: root
                password: yrd1997523
#启动的端口
server:
        port: 8888